//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 03:27:25 com.asiainfo.integretion.o2p.serviceagent.cache.IMemcacheManageServ CST 
//


package com.asiainfo.integretion.o2p.servicemigration.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attrValue", propOrder = {
    "attrValueCode",
    "name",
    "value",
    "status"
})
public class AttrValue extends BasedBean {

    @XmlElement(required = true)
    protected String attrValueCode;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String value;
    @XmlElement(required = true)
    protected String status;

    /**
     * Gets the value of the attrValueCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrValueCode() {
        return attrValueCode;
    }

    /**
     * Sets the value of the attrValueCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrValueCode(String value) {
        this.attrValueCode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

	@Override
	public boolean equals(Object obj) {
		if(!(obj instanceof AttrValue)) {
			return false;
		}
		if(this.getAttributes() != null && this.getAttributes().get("parentBean") != null) {
			boolean isEquals = super.equals(obj);
			if(isEquals) {
				String codeValue = ((BasedBean)this.getAttributes().get("parentBean")).codeValue();
				if(((BasedBean)obj).getAttributes() != null && ((BasedBean)obj).getAttributes().get("parentBean") != null) {
					String tcodeValue = ((BasedBean)((BasedBean)obj).getAttributes().get("parentBean")).codeValue();
					return CommonUtil.compareOrdinaryAttr(codeValue, tcodeValue);
				}
				return true;
			} else {
				return false;
			}
		} else {
			return super.equals(obj);
		}
	}

	@Override
	public int hashCode(){
		return super. hashCode();
	}
}
