//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 03:27:25 com.asiainfo.integretion.o2p.serviceagent.cache.IMemcacheManageServ CST 
//


package com.asiainfo.integretion.o2p.servicemigration.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.asiainfo.integretion.o2p.servicemigration.common.jaxbAdapter.JaxbDateAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileDirectory", propOrder = {
    "fileDirectoryCode",
    "upDirectory",
    "remoteAuth",
    "directoryPath",
    "directoryType",
    "utlPath",
    "createTime",
    "description"
})
public class FileDirectory extends BasedBean {

    @XmlElement(required = true)
    protected String fileDirectoryCode;
    protected FileDirectory upDirectory;
    @XmlElement(required = true)
    protected RemoteHostAuthentication remoteAuth;
    @XmlElement(required = true)
    protected String directoryPath;
    @XmlElement(required = true)
    protected String directoryType;
    protected String utlPath;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(JaxbDateAdapter.class)
    protected XMLGregorianCalendar createTime;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the fileDirectoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDirectoryCode() {
        return fileDirectoryCode;
    }

    /**
     * Sets the value of the fileDirectoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDirectoryCode(String value) {
        this.fileDirectoryCode = value;
    }

    /**
     * Gets the value of the upDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link FileDirectory }
     *     
     */
    public FileDirectory getUpDirectory() {
        return upDirectory;
    }

    /**
     * Sets the value of the upDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileDirectory }
     *     
     */
    public void setUpDirectory(FileDirectory value) {
        this.upDirectory = value;
    }

    /**
     * Gets the value of the remoteAuth property.
     * 
     * @return
     *     possible object is
     *     {@link RemoteHostAuthentication }
     *     
     */
    public RemoteHostAuthentication getRemoteAuth() {
        return remoteAuth;
    }

    /**
     * Sets the value of the remoteAuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoteHostAuthentication }
     *     
     */
    public void setRemoteAuth(RemoteHostAuthentication value) {
        this.remoteAuth = value;
    }

    /**
     * Gets the value of the directoryPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryPath() {
        return directoryPath;
    }

    /**
     * Sets the value of the directoryPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryPath(String value) {
        this.directoryPath = value;
    }

    /**
     * Gets the value of the directoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryType() {
        return directoryType;
    }

    /**
     * Sets the value of the directoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryType(String value) {
        this.directoryType = value;
    }

    /**
     * Gets the value of the utlPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtlPath() {
        return utlPath;
    }

    /**
     * Sets the value of the utlPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtlPath(String value) {
        this.utlPath = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateTime(XMLGregorianCalendar value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

	@Override
	public boolean equals(Object obj){
		return super.equals(obj);
	}

	@Override
	public int hashCode(){
		return super. hashCode();
	}
}
