//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 03:27:25 com.asiainfo.integretion.o2p.serviceagent.cache.IMemcacheManageServ CST 
//

package com.asiainfo.integretion.o2p.servicemigration.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.asiainfo.integretion.o2p.servicemigration.common.annotation.ReferenceType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceTechnologyImplementType", propOrder = {
		"technologyImplementCode", "apiCode" })
public class ServiceTechnologyImplement extends BasedBean {
	@XmlElement(required = true)
	@ReferenceType(TechnologyImplement.class)
	private String technologyImplementCode;
	@XmlElement(required = true)
	@ReferenceType(Api.class)
	private String apiCode;

	public String getTechnologyImplementCode() {
		return technologyImplementCode;
	}

	public void setTechnologyImplementCode(String technologyImplementCode) {
		this.technologyImplementCode = technologyImplementCode;
	}

	public String getApiCode() {
		return apiCode;
	}

	public void setApiCode(String apiCode) {
		this.apiCode = apiCode;
	}

//	@Override
//	public String getCode() {
//		return null;
//	}

	@Override
	public boolean equals(Object obj){
		return super.equals(obj);
	}

	@Override
	public int hashCode(){
		return super.hashCode();
	}
}
